### ISSUE TITLE
2 sungrow inverter

### ISSUE THREAD

**Issue by urueedi** [alangibson/homeassistant-sungrow#1]
Thank you for your work, at the moment is not possible to add more then one sungrow inverter. I have 2 sungrow inverter 1x sg40cx + 1x sg50cx.

**Comment by AlexanderLanin** [comment]
It's not working for other reasons, but I can add two:
![image](https://github.com/alangibson/homeassistant-sungrow/assets/5074553/b276fe5d-bfa4-40d2-b7a4-4b14ca5fce44)

**Comment by AlexanderLanin** [comment]
Fixed the other problem (unsupported inverter, see https://github.com/bohdan-s/SunGather/issues/157).
Anyway, now I see the following:
```
Platform sungrow does not generate unique IDs. ID sungrow_16690_meter_power already exists - ignoring sensor.sh80rt_20_16690_current_meter_power
Platform sungrow does not generate unique IDs. ID sungrow_16690_total_active_power already exists - ignoring sensor.sh80rt_20_16690_current_active_power
Platform sungrow does not generate unique IDs. ID sungrow_16690_export_to_grid already exists - ignoring sensor.sh80rt_20_16690_current_power_exported_to_grid
[...]
```

**Comment by AlexanderLanin** [comment]
Note: I've checked the content of "serial_number" just after scraping:
```
2023-12-22 03:43:07.753 WARNING (SyncWorker_4) [custom_components.sungrow.SunGather.inverter] (192.168.13.80:502 (2)) serial_number: 16690
2023-12-22 03:43:07.854 WARNING (SyncWorker_5) [custom_components.sungrow.SunGather.inverter] (192.168.13.79:502 (1)) serial_number: 16690
```

I don't know if that's normal...

Inverters connected via modbus.

- master: 192.168.13.79:502 (slave 1)
- slave: 192.168.13.80:502 (slave 2)

**Comment by alangibson** [comment]
@AlexanderLanin I'm looking at the unsupported inverter problem now. What fix did you do?

**Comment by alangibson** [comment]
Two devices getting the same serial number is very odd. In config_flow.py:

```
async def async_step_user(self, user_input=None):
    ...
    unique_device_id = inverter.latest_scrape.get('serial_number')
```

So this gets fixed at setup time. I need to look deeper on this one.

**Comment by AlexanderLanin** [comment]
> So this gets fixed at setup time. I need to look deeper on this one.

I logged it directly in load_registers():
```
                    if register_name == "serial_number":
                        logger.warning(f"serial_number: {register_value}")
```

It's the same value.

**Comment by AlexanderLanin** [comment]
> @AlexanderLanin I'm looking at the unsupported inverter problem now. What fix did you do?

https://github.com/bohdan-s/SunGather/issues/157#issuecomment-1867811522

**Comment by AlexanderLanin** [comment]
@alangibson Ah found it. It's 10 registers, not one. And I actually get exactly the number that is printed on the side of the inverter!

```
result = client.read_input_registers(4989, count=10, unit=unit)
serial_number = "".join([chr(c >> 8) + chr(c & 0xFF) for c in result.registers])
```
